# The backend specifies how to connect to your GitHub repo.
backend:
  name: github
  repo: ZaZza402/AxiomWeb # e.g., "Mikaela/my-website-with-cms"
  branch: main # Or "master" if that's your default branch

# The media_folder is where all uploaded images and files will be stored.
media_folder: "assets/uploads" # A folder named "assets/uploads" will be created
public_folder: "/assets/uploads" # The public-facing path to the media folder

# The collections are the different types of content you can create.
# We will start with one collection: "Blog".
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The folder where the documents will be stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document, like the form for creating a post.
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}